export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_TOKEN = "SET_TOKEN";
export const SET_LOADER = "SET_LOADER";
export const SET_LOGOUT = "SET_LOGOUT";
export const SET_FORGOT_PASSWROD_EMAIL = "SET_FORGOT_PASSWROD_EMAIL";